//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Users1 = new HashSet<Users>();
            this.Orders = new HashSet<Orders>();
            this.PaymentHistory = new HashSet<PaymentHistory>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string MiddleName { get; set; }
        public byte[] Foto { get; set; }
        public string Email { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int UserTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ICollection<Users> Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<PaymentHistory> PaymentHistory { get; set; }
    }
}
