//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Managers
    {
        public Managers()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string MiddleName { get; set; }
        public decimal Salary { get; set; }
        public byte[] Foto { get; set; }
        public double SalaryPercent { get; set; }
    
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
